version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: order_test_nginx
    ports:
      - "${WEB_PORT:-8282}:80"
    volumes:
      - ./application:/var/www/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - application

  php:
    container_name: order_test_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./application:/var/www/application
      - ./migrations:/var/www/migrations
      - ./sql_dump:/var/www/sql_dump
    environment:
      APP_ENV: '${ENV:-dev}'
      DB_HOST: '${DB_HOST:-db}'
      DB_NAME: '${DB_NAME:-order_test}'
      DB_USER: '${DB_USER:-root}'
      DB_PASSWORD: '${DB_PASSWORD:-psh_psh_ololo_ya_voditel_nlo}'
      LANGUAGE: '${APP_LANGUAGE:-en}'
    depends_on:
      - db
    networks:
      - application

  db:
    image: mysql:8.0
    container_name: order_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-psh_psh_ololo_ya_voditel_nlo}'
      MYSQL_DATABASE: '${DB_NAME:-order_test}'
      MYSQL_USER: '${DB_USER:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-psh_psh_ololo_ya_voditel_nlo}'
    ports:
      - "${DB_PORT:-3309}:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - application

networks:
  application:
    driver: bridge
